### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by pakcybershagufta** [yedincisenol/laravel-api-startup#10]
@yedincisenol  Key file "file://D:\wamp64\www\laravel-api-startup\storage\oauth-private.key" permissions are not correct, should be 600 or 660 instead of 666

**Comment by pakcybershagufta** [comment]
@yedincisenol 
Key file "file://D:\wamp64\www\laravel-api-startup\storage\oauth-private.key" permissions are not correct, should be 600 or 660 instead of 666

**Comment by yedincisenol** [comment]
@pakcybershagufta Can you upgrade passport version to: 'v3.0.1' and run 
`composer update`
